#!/bin/bash

source "$PWD"/function
source "$PWD"/config

mkdir -p rootfs/bin rootfs/etc/init.d rootfs/include rootfs/lib rootfs/mnt \
	rootfs/proc rootfs/run rootfs/tmp rootfs/sys rootfs/var/{db,log,tmp}

mkdir "$SRCDIR"
mkdir "$TMPDIR"

for bin in wget make gcc bc grub-mkrescue ; do
	if ! exist $bin ; then
		echo $bin not found, you may need to install it.
	fi
done
