#!/bin/bash

source "$PWD"/config

cd "$SRCDIR"

tar -xf "linux-${KERNEL_VER}.tar.xz"
cd "linux-${KERNEL_VER}"

case $KERNEL_CONFIG in

	giantrock)	cp "$BASEDIR"/giantrock.kcfg .config ;;
	custom)   	cp "$BASEDIR/$_KERNEL_CUSTOM_CONFIG_FILE" ;;
	defconfig)	make $MAKEFLAGS defconfig ;;
	mrproper)	make $MAKEFLAGS mrproper ;;
	menuconfig)	make $MAKEFLAGS menuconfig ;;
	*)	echo "Invaild KERNEL_CONFIG=${KERNEL_CONFIG}" ;;
esac

make $MAKEFLAGS

if grep \=m .config 2>&1 > /dev/null ; then
make INSTALL_MOD_PATH="${BASEDIR}/rootfs"
fi

cp -L arch/x86_64/boot/bzImage "$BASEDIR/tmp"
