#!/bin/bash

source "$PWD"/config

cd "$SRCDIR"

tar -xf "glibc-${GLIBC_VER}.tar.xz"
cd glibc-${GLIBC_VER}
mkdir build && cd build

../configure --prefix=/ LDFLAGS="${_LDFLAGS}" CFLAGS="${_CFLAGS}"
make $MAKEFLAGS
make DESTDIR="${BASEDIR}/rootfs" install

