#!/bin/bash

source "$PWD"/config

cd "$SRCDIR"

tar -xf "tcc-${TCC_VER}.tar.bz2"
cd tcc-${TCC_VER}

./configure --extra-cflags="$_CFLAGS" --extra-ldflags="$_LDFLAGS" --prefix=/

make $MAKEFLAGS
make DESTDIR="${BASEDIR}/rootfs" $MAKEFLAGS install
