#!/bin/bash

source "$PWD"/function
source "$PWD"/config

cp "$TMPDIR/sash" "$TMPDIR/busybox" "$BASEDIR/rootfs/bin/"
cp "$TMPDIR/bzImage" "$BASEDIR/boot/"

cd "$BASEDIR/rootfs"
ln -s busybox bin/sh
ln -s busybox bin/hush
ln -s busybox bin/init

cp -rv "$BASEDIR"/overlay/* rootfs/
