#!/bin/bash

source "$PWD"/config

if [ ! $EUID == 0 ] ; then
	echo "You need to run this part as root."
	exit 0
fi

cd "$BASEDIR/rootfs"
chmod -Rfv 0755 .
chown -Rfv 0:0 .
find . | cpio -ov -H newc --no-absolute-filenames | {
case INITRAMFS_COMPRESS in
	xz)	nice -n 19 xz -zcvv --check=crc32 -T0;;
	lz4)	nice -n 19 lz4 -l -zcvv;;
	gz)	nice -n 19 gzip -cv;;
	lzo)	nice -n 19 lzop -cv;;
	bzip2)	nice -n 19 bzip2 -zcvv;;
} > "$BASEDIR/boot/initramfs"
